version: '3.7'

services:
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./mongodb-data:/data/db