version: '3.7'

services:
  mysql-docker:
    image: mysql/mysql-server
    ports:
      - '3306:3306'
    expose:
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mydb'
      MYSQL_USER: 'mytestuser'
      MYSQL_PASSWORD: 'mypassword'
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./db/backup/:/mysql/backup
      - ./db/init:/docker-entrypoint-initdb.d